### ISSUE TITLE
Komolgorov-Smirnov test introduction

### ISSUE THREAD

**Issue by anonymous2020andbeyond** [learn-co-curriculum/dsc-kolmogorov-smirnov-test#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6222/pages/the-kolmogorov-smirnov-test?module_item_id=529274

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

This is an extremely confusing lesson.  While it is helpful to see how the calculations for the 1-test example (against theoretical) how are made (and I recommend keeping that), it would be helpful to see what the equivalent code would be.  
My biggest objection is with the two-sample test.  First the rendering is not good the X and Y cases are laid out linearly rather than on separate lines.  And its unclear of the numbers listed are as-is random numbers that have been sorted or if each number has already been sorted and added to the consecutive number.  Likewise there is no clarity into how the Fx and Fy are calculated.  It would be really helpful especially since now we have two samples with different numbers of observations why you need to combine the two samples of X and Y before you do the Fx and Fy calculations, and how you do the Fx and Fy calculations.

## What OS Are You Using?

- [ ] OS X
- [X ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
This lesson is no longer part of the curriculum as of v3.0. As such, we won't be updating the repo. Thank you for pointing out your concerns with the lesson; I don't disagree with them.
